### PR TITLE
Update to PK-Sim 10

### PR DESCRIPTION
**Pull request by sfrechen**
Update to PK-Sim 10 including update of GABRG2 and ATP1A2 reference concentrations and OATP1B1 kcat value to account for pk-sim 10 update in interstitial concentration calculations.

### CODE REVIEW

**Comment by Yuri05** [comment]
@sfrechen Something looks strange in the snapshot.
On the left you see the V9 snapshot imported in V10 and then exported without changes (this one: [V9_to_V10_Rifampicin-Verapamil-DDI.zip](https://github.com/Open-Systems-Pharmacology/Rifampicin-Verapamil-DDI/files/7154607/V9_to_V10_Rifampicin-Verapamil-DDI.zip))

On the right the V10 snapshot from the PR
grafik

grafik

**Comment by Yuri05** [comment]
yes, something is very wrong with the snapshot in the PR.
grafik
grafik

@sfrechen Did you create this snapshot via PK-Sim **only** or did you use any scripts or manual editing?

**Comment by sfrechen** [comment]
@Yuri05 
No scripts. Manual editing for the 3 parameters specified.

Redone now with PK-Sim 10.0.219. Still issues?

**Comment by Yuri05** [comment]
The last one is good. hope we don't have issues here

**Pull request merged**
